// packages/vike-layouts/vue/shells/SidebarShell.vue
<script setup>
import NavList from './NavList.vue'
const props = defineProps({
  layout: { type: Object, default: () => ({ dir: 'ltr', slots: {} }) },
})
</script>
<template>
  <div :dir="props.layout.dir" :style="{ minHeight: '100vh', display: 'flex', background: 'var(--color-bg)', color: 'var(--color-text)', fontFamily: 'var(--font-sans)' }">
    <aside :style="{ width: '220px', flexShrink: 0, display: 'flex', flexDirection: 'column', gap: 'var(--space-lg, 2rem)', padding: 'var(--space-lg, 2rem)', borderInlineEnd: '1px solid var(--color-border)', background: 'var(--color-surface)' }">
      <strong v-if="props.layout.slots?.logo">{{ props.layout.slots.logo }}</strong>
      <NavList :items="props.layout.slots?.nav" :vertical="true" />
      <div :style="{ marginTop: 'auto' }">{{ props.layout.slots?.userMenu }}</div>
    </aside>
    <main :style="{ flex: 1, padding: 'var(--space-lg, 2rem)' }">
      <slot />
    </main>
  </div>
</template>

// packages/vike-react-layouts/shells/SidebarShell.jsx
// Sidebar app shell — signed-in chrome with vertical nav down the leading side
// (logo on top, user menu at the bottom), content in the main column.
import { NavList } from './NavList.jsx'

export function SidebarShell({ layout = { dir: 'ltr', slots: {} }, children }) {
  const { logo, nav, userMenu } = layout.slots || {}
  return (
    <div
      dir={layout.dir}
      style={{
        minHeight: '100vh',
        display: 'flex',
        background: 'var(--color-bg)',
        color: 'var(--color-text)',
        fontFamily: 'var(--font-sans)',
      }}
    >
      <aside
        style={{
          width: 220,
          flexShrink: 0,
          display: 'flex',
          flexDirection: 'column',
          gap: 'var(--space-lg, 2rem)',
          padding: 'var(--space-lg, 2rem)',
          borderInlineEnd: '1px solid var(--color-border)',
          background: 'var(--color-surface)',
        }}
      >
        {logo && <strong>{logo}</strong>}
        <NavList items={nav} vertical />
        <div style={{ marginTop: 'auto' }}>{userMenu}</div>
      </aside>
      <main style={{ flex: 1, padding: 'var(--space-lg, 2rem)' }}>{children}</main>
    </div>
  )
}
