// packages/vike-push/vue/PushToggle.vue
<script setup>
// <PushToggle> - the Vue subscribe control, the twin of vike-push/react/PushToggle.
// Thin wrapper over the framework-agnostic client helpers (vike-push/client); imports
// nothing server-side. The VAPID public key comes from the prop or the app's
// `vapidPublicKey` config off pageContext.
import { ref, onMounted } from 'vue'
import { usePageContext } from 'vike-vue/usePageContext'
import { isPushSupported, subscribe, unsubscribe, getExistingSubscription } from '../client.js'

const props = defineProps({
  vapidPublicKey: { type: String, default: '' },
  swUrl: { type: String, default: '/vike-push-sw.js' },
  label: { type: String, default: 'Notifications' },
})

const pageContext = usePageContext()
const key = props.vapidPublicKey || pageContext?.config?.vapidPublicKey

const supported = ref(false)
const subscribed = ref(false)
const busy = ref(false)
const error = ref(null)

onMounted(async () => {
  supported.value = isPushSupported()
  try {
    subscribed.value = !!(await getExistingSubscription())
  } catch {
    // ignore
  }
})

async function onClick() {
  busy.value = true
  error.value = null
  try {
    if (subscribed.value) {
      await unsubscribe({})
      subscribed.value = false
    } else {
      await subscribe({ vapidPublicKey: key, swUrl: props.swUrl })
      subscribed.value = true
    }
  } catch (e) {
    error.value = e?.message || 'Something went wrong'
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <span v-if="!supported" :style="{ color: 'var(--color-muted)', fontSize: '13px' }">Push not supported here</span>
  <span v-else :style="{ display: 'inline-flex', alignItems: 'center', gap: '8px' }">
    <button
      type="button"
      @click="onClick"
      :disabled="busy"
      :style="{
        padding: '0.35rem 0.7rem',
        borderRadius: 'var(--radius, 10px)',
        border: '1px solid var(--color-border)',
        background: subscribed ? 'var(--color-surface)' : 'var(--color-primary)',
        color: subscribed ? 'var(--color-text)' : 'var(--color-primary-text, #fff)',
        fontSize: '13px',
        cursor: busy ? 'default' : 'pointer',
        opacity: busy ? 0.7 : 1,
      }"
    >
      {{ busy ? '...' : subscribed ? `Disable ${label}` : `Enable ${label}` }}
    </button>
    <span v-if="error" :style="{ color: '#dc2626', fontSize: '12px' }">{{ error }}</span>
  </span>
</template>

// packages/vike-push/react/PushToggle.jsx
// <PushToggle> - the React subscribe control. A button that enables/disables Web Push
// notifications for the signed-in user. Thin wrapper over the framework-agnostic client
// helpers (vike-push/client); imports nothing server-side.
//
// The VAPID public key comes from the `vapidPublicKey` prop, or the app's
// `vapidPublicKey` config off pageContext (declared in vike-push/config). The service
// worker URL defaults to /vike-push-sw.js (served from the app's public/).
import { useState, useEffect } from 'react'
import { usePageContext } from 'vike-react/usePageContext'
import { isPushSupported, subscribe, unsubscribe, getExistingSubscription } from '../client.js'

export function PushToggle({ vapidPublicKey, swUrl = '/vike-push-sw.js', label = 'Notifications' }) {
  const pageContext = usePageContext()
  const key = vapidPublicKey || pageContext?.config?.vapidPublicKey
  const [supported, setSupported] = useState(false)
  const [subscribed, setSubscribed] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)

  useEffect(() => {
    setSupported(isPushSupported())
    getExistingSubscription().then((s) => setSubscribed(!!s)).catch(() => {})
  }, [])

  if (!supported) {
    return <span style={{ color: 'var(--color-muted)', fontSize: 13 }}>Push not supported here</span>
  }

  async function onClick() {
    setBusy(true)
    setError(null)
    try {
      if (subscribed) {
        await unsubscribe({})
        setSubscribed(false)
      } else {
        await subscribe({ vapidPublicKey: key, swUrl })
        setSubscribed(true)
      }
    } catch (e) {
      setError(e?.message || 'Something went wrong')
    } finally {
      setBusy(false)
    }
  }

  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
      <button
        type="button"
        onClick={onClick}
        disabled={busy}
        style={{
          padding: '0.35rem 0.7rem',
          borderRadius: 'var(--radius, 10px)',
          border: '1px solid var(--color-border)',
          background: subscribed ? 'var(--color-surface)' : 'var(--color-primary)',
          color: subscribed ? 'var(--color-text)' : 'var(--color-primary-text, #fff)',
          fontSize: 13,
          cursor: busy ? 'default' : 'pointer',
          opacity: busy ? 0.7 : 1,
        }}
      >
        {busy ? '...' : subscribed ? `Disable ${label}` : `Enable ${label}`}
      </button>
      {error && <span style={{ color: '#dc2626', fontSize: 12 }}>{error}</span>}
    </span>
  )
}

export default PushToggle
