// packages/vike-auth/react/AccountPage.jsx
// The /account PAGE, shipped by the extension (config.pages). Shows the signed-in
// user (resolved by the vike-auth server tier into pageContext.user) with a logout
// control, or a prompt to sign in. Reads one field via useUser(); never touches
// sessions/tokens.
import { useUser } from './useUser.js'
import { UserButton } from './UserButton.jsx'
import { useTranslation } from 'vike-i18n/react/hooks'
import { authMessages } from './messages.js'

const card = {
  border: '1px solid var(--color-border)',
  background: 'var(--color-surface)',
  borderRadius: 'var(--radius, 10px)',
  padding: 'var(--space-lg, 1.5rem)',
  marginTop: 'var(--space-md, 1rem)',
}
const row = { display: 'flex', gap: '0.5rem', fontSize: 14, lineHeight: 1.9 }
const label = { color: 'var(--color-muted)', minWidth: 110 }

export default function AccountPage() {
  const user = useUser()
  const { t } = useTranslation(authMessages.en)

  return (
    <div style={{ maxWidth: 640, margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h1 style={{ margin: 0, fontSize: 22 }}>{t('auth.accountTitle')}</h1>
        <UserButton />
      </div>

      {user ? (
        <div style={card}>
          <div style={row}>
            <span style={label}>{t('auth.accountSignedInAs')}</span>
            <strong style={{ color: 'var(--color-text)' }}>{user.email}</strong>
          </div>
          {user.name && (
            <div style={row}>
              <span style={label}>{t('auth.accountName')}</span>
              <span style={{ color: 'var(--color-text)' }}>{user.name}</span>
            </div>
          )}
        </div>
      ) : (
        <p style={{ color: 'var(--color-muted)', marginTop: 'var(--space-md, 1rem)' }}>
          {t('auth.accountSignedOut')}{' '}
          <a href="/login" style={{ color: 'var(--color-primary)' }}>
            {t('auth.signInShort')}
          </a>
        </p>
      )}
    </div>
  )
}

// packages/vike-auth/vue/AccountPage.vue
<script setup>
import { useUser } from './useUser.js'
import UserButton from './UserButton.vue'
import { useTranslation } from 'vike-i18n/vue/hooks'
import { authMessages } from './messages.js'

const user = useUser()
const { t } = useTranslation(authMessages.en)
</script>
<template>
  <div :style="{ maxWidth: '640px', margin: '0 auto' }">
    <div :style="{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }">
      <h1 :style="{ margin: 0, fontSize: '22px' }">{{ t('auth.accountTitle') }}</h1>
      <UserButton />
    </div>
    <div v-if="user" :style="{ border: '1px solid var(--color-border)', background: 'var(--color-surface)', borderRadius: 'var(--radius, 10px)', padding: 'var(--space-lg, 1.5rem)', marginTop: 'var(--space-md, 1rem)' }">
      <div :style="{ display: 'flex', gap: '0.5rem', fontSize: '14px', lineHeight: 1.9 }">
        <span :style="{ color: 'var(--color-muted)', minWidth: '110px' }">{{ t('auth.accountSignedInAs') }}</span>
        <strong :style="{ color: 'var(--color-text)' }">{{ user.email }}</strong>
      </div>
      <div v-if="user.name" :style="{ display: 'flex', gap: '0.5rem', fontSize: '14px', lineHeight: 1.9 }">
        <span :style="{ color: 'var(--color-muted)', minWidth: '110px' }">{{ t('auth.accountName') }}</span>
        <span :style="{ color: 'var(--color-text)' }">{{ user.name }}</span>
      </div>
    </div>
    <p v-else :style="{ color: 'var(--color-muted)', marginTop: 'var(--space-md, 1rem)' }">
      {{ t('auth.accountSignedOut') }}
      <a href="/login" :style="{ color: 'var(--color-primary)' }">{{ t('auth.signInShort') }}</a>
    </p>
  </div>
</template>
