// packages/vike-storage/vue/FileUpload.vue
<script setup>
// <FileUpload> - the Vue upload control, the twin of vike-storage/react/FileUpload. A file
// input that uploads the chosen file to /uploads and emits `uploaded` with the stored record.
// Thin wrapper over the framework-agnostic client helpers (vike-storage/client); imports
// nothing server-side.
//
// The vike-admin `file` WIDGET (so an `.as('file')` column renders this in the admin form) is
// React-only for now; it lands for Vue once vike-admin ships a Vue widget registry (the fast
// follow noted with #177). This standalone control works today.
import { ref } from 'vue'
import { uploadFile } from '../client.js'

const props = defineProps({
  uploadUrl: { type: String, default: '/uploads' },
  label: { type: String, default: 'Upload a file' },
  accept: { type: String, default: undefined },
})
const emit = defineEmits(['uploaded'])

const busy = ref(false)
const error = ref(null)
const done = ref(null)

async function onChange(e) {
  const file = e.target.files?.[0]
  if (!file) return
  busy.value = true
  error.value = null
  try {
    const saved = await uploadFile(file, { uploadUrl: props.uploadUrl })
    done.value = saved
    emit('uploaded', saved)
  } catch (err) {
    error.value = err?.message || 'Upload failed'
  } finally {
    busy.value = false
  }
}
</script>

<template>
  <span :style="{ display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '13px' }">
    <label :style="{ color: 'var(--color-muted)' }">
      {{ label }}
      <input type="file" :accept="accept" :disabled="busy" @change="onChange" />
    </label>
    <span v-if="busy" :style="{ color: 'var(--color-muted)' }">Uploading...</span>
    <a v-else-if="done" :href="done.url" target="_blank" rel="noreferrer" :style="{ color: 'var(--color-primary)' }">
      {{ done.filename || 'view' }}
    </a>
    <span v-if="error" :style="{ color: '#dc2626' }">{{ error }}</span>
  </span>
</template>

// packages/vike-storage/react/FileUpload.jsx
// <FileUpload> - the React upload control (the standalone analog of vike-push's PushToggle).
// A file input that uploads the chosen file to /uploads and reports the stored URL through
// onUploaded. Thin wrapper over the framework-agnostic client helpers (vike-storage/client);
// imports nothing server-side, so it is safe in the client bundle.
//
// For the vike-admin form field (an `.as('file')` column), see ./FileField.jsx, which wraps
// this same upload flow into a registry widget.
import { useState } from 'react'
import { uploadFile } from '../client.js'

export function FileUpload({ onUploaded, uploadUrl = '/uploads', label = 'Upload a file', accept }) {
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)
  const [done, setDone] = useState(null)

  async function onChange(e) {
    const file = e.target.files?.[0]
    if (!file) return
    setBusy(true)
    setError(null)
    try {
      const saved = await uploadFile(file, { uploadUrl })
      setDone(saved)
      onUploaded?.(saved)
    } catch (err) {
      setError(err?.message || 'Upload failed')
    } finally {
      setBusy(false)
    }
  }

  return (
    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 13 }}>
      <label style={{ color: 'var(--color-muted)' }}>
        {label}{' '}
        <input type="file" accept={accept} onChange={onChange} disabled={busy} />
      </label>
      {busy && <span style={{ color: 'var(--color-muted)' }}>Uploading...</span>}
      {done && !busy && (
        <a href={done.url} target="_blank" rel="noreferrer" style={{ color: 'var(--color-primary)' }}>
          {done.filename || 'view'}
        </a>
      )}
      {error && <span style={{ color: '#dc2626' }}>{error}</span>}
    </span>
  )
}

export default FileUpload
