// packages/vike-toolbar/react/Toolbar.jsx
// The toolbar surface: a fixed Vike-logo button that toggles a panel of settings.
// It renders into the `bodyHtmlEnd` mount node (`#vike-toolbar-root`, outside the
// hydration root), which is why portaling extension controls into it is safe — no
// React root hydrates that subtree.
//
// The panel holds two kinds of control:
//   - simple `toolbarItems` the toolbar renders itself (context-free), and
//   - `#vike-toolbar-items`: the teleport target other extensions portal their own LIVE
//     controls into (vike-themes' picker, vike-i18n's switcher), so each keeps its
//     provider context. React renders this node empty and never reconciles its children,
//     so the externally-teleported nodes are left intact across open/close re-renders.
import { useState } from 'react'
import { createPortal } from 'react-dom'
import { usePortalTarget } from './usePortalTarget.js'
import logoUrl from './vike-logo.svg'

const ROOT_ID = 'vike-toolbar-root'

const panelStyle = {
  position: 'absolute',
  bottom: 'calc(100% + 8px)',
  insetInlineStart: 0,
  minWidth: 220,
  flexDirection: 'column',
  gap: 12,
  padding: '0.75rem 0.85rem',
  borderRadius: 'var(--radius, 10px)',
  border: '1px solid var(--color-border)',
  background: 'var(--color-surface)',
  color: 'var(--color-text)',
  fontSize: 13,
  fontFamily: 'var(--font-sans)',
  boxShadow: '0 2px 12px rgba(0,0,0,0.14)',
}

export function Toolbar({ items = [] }) {
  const root = usePortalTarget(ROOT_ID)
  const [open, setOpen] = useState(false)
  if (!root) return null // server + until the bodyHtmlEnd node resolves client-side

  return createPortal(
    <div style={{ position: 'fixed', bottom: 16, insetInlineStart: 16, zIndex: 50, fontFamily: 'var(--font-sans)' }}>
      <div role="dialog" aria-label="Settings" style={{ ...panelStyle, display: open ? 'flex' : 'none' }}>
        {items.map(({ id, label, Control }) => (
          <div key={id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12 }}>
            {label && <span style={{ color: 'var(--color-muted)' }}>{label}</span>}
            <Control />
          </div>
        ))}
        {/* Teleport target for other extensions' live controls. Rendered empty + with
            display:contents so its (externally-portaled) children flow into the panel. */}
        <div id="vike-toolbar-items" style={{ display: 'contents' }} />
      </div>
      <button
        type="button"
        aria-label="Settings"
        aria-expanded={open}
        onClick={() => setOpen((v) => !v)}
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: 44,
          height: 44,
          padding: 0,
          borderRadius: '50%',
          border: '1px solid var(--color-border)',
          background: 'var(--color-surface)',
          cursor: 'pointer',
          boxShadow: '0 1px 6px rgba(0,0,0,0.12)',
        }}
      >
        <img src={logoUrl} alt="" width="24" height="24" style={{ display: 'block' }} />
      </button>
    </div>,
    root,
  )
}

// packages/vike-toolbar/vue/Toolbar.vue
<script setup>
import { ref, onMounted } from 'vue'
import logoSvg from './vike-logo.svg?raw'

const props = defineProps({
  items: { type: Array, default: () => [] },
})

const ROOT_ID = 'vike-toolbar-root'
const open = ref(false)
const root = ref(null)

const logoMarkup = logoSvg.replace('width="38"', 'width="24"').replace('height="38"', 'height="24"')

onMounted(() => {
  const el = document.getElementById(ROOT_ID)
  if (el) { root.value = el; return }
  const obs = new MutationObserver(() => {
    const node = document.getElementById(ROOT_ID)
    if (node) { root.value = node; obs.disconnect() }
  })
  obs.observe(document.body, { childList: true, subtree: true })
})

const FIXED = { position: 'fixed', insetInlineStart: '16px', zIndex: 50, fontFamily: 'var(--font-sans)' }
</script>
<template>
  <Teleport v-if="root" :to="root">
    <div
      role="dialog"
      aria-label="Settings"
      :style="{ ...FIXED, bottom: '72px', minWidth: '220px', flexDirection: 'column', gap: '12px', padding: '0.75rem 0.85rem', borderRadius: 'var(--radius, 10px)', border: '1px solid var(--color-border)', background: 'var(--color-surface)', color: 'var(--color-text)', fontSize: '13px', boxShadow: '0 2px 12px rgba(0,0,0,0.14)', display: open ? 'flex' : 'none' }"
    >
      <div v-for="item in props.items" :key="item.id" :style="{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' }">
        <span v-if="item.label" :style="{ color: 'var(--color-muted)' }">{{ item.label }}</span>
        <component :is="item.Control" />
      </div>
      <!-- Teleport target for other extensions' live controls. Empty + display:contents
           so its (externally-teleported) children flow into the panel's column. -->
      <div id="vike-toolbar-items" :style="{ display: 'contents' }" />
    </div>
  </Teleport>
  <button
    type="button"
    aria-label="Open settings"
    :aria-expanded="open"
    @click="open = !open"
    :style="{ ...FIXED, bottom: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', width: '44px', height: '44px', padding: 0, borderRadius: '50%', border: '1px solid var(--color-border)', background: 'var(--color-surface)', cursor: 'pointer', boxShadow: '0 1px 6px rgba(0,0,0,0.12)' }"
  >
    <span aria-hidden="true" :style="{ display: 'flex', width: '24px', height: '24px' }" v-html="logoMarkup" />
  </button>
</template>
