// packages/vike-auth/vue/SignInForm.vue
<script setup>
import { ref } from 'vue'
import { useTranslation } from 'vike-i18n/vue/hooks'
import { authMessages } from './messages.js'

const props = defineProps({
  action: { type: String, default: '/auth/request' },
  appName: { type: String, default: 'Acme' },
})

const { t } = useTranslation(authMessages.en)
const email = ref('')
const state = ref('idle') // idle | sending | sent | error

async function onSubmit(e) {
  e.preventDefault()
  state.value = 'sending'
  try {
    const body = new FormData()
    body.set('email', email.value)
    const next = new URLSearchParams(window.location.search).get('next')
    if (next) body.set('next', next)
    const res = await fetch(props.action, { method: 'POST', body })
    state.value = res.ok ? 'sent' : 'error'
  } catch {
    state.value = 'error'
  }
}

const field = {
  width: '100%',
  boxSizing: 'border-box',
  padding: '0.6rem 0.7rem',
  marginTop: '0.35rem',
  borderRadius: 'var(--radius, 10px)',
  border: '1px solid var(--color-border)',
  background: 'var(--color-bg)',
  color: 'var(--color-text)',
  fontSize: '14px',
}
const primaryBtn = {
  width: '100%',
  marginTop: 'var(--space-md, 1rem)',
  padding: '0.6rem 0.7rem',
  borderRadius: 'var(--radius, 10px)',
  border: '1px solid transparent',
  background: 'var(--color-primary)',
  color: 'var(--color-primary-text)',
  fontWeight: 600,
  fontSize: '14px',
  cursor: 'pointer',
}
</script>

<template>
  <div v-if="state === 'sent'">
    <h1 :style="{ margin: '0 0 0.5rem', fontSize: '20px' }">{{ t('auth.inboxTitle') }}</h1>
    <p :style="{ color: 'var(--color-muted)', fontSize: '14px', lineHeight: 1.6 }">
      {{ t('auth.inboxBody', { email: email }) }} {{ t('auth.devNote') }}
    </p>
    <button type="button" :style="{ ...primaryBtn, background: 'transparent', color: 'var(--color-primary)', border: '1px solid var(--color-border)' }" @click="state = 'idle'">
      {{ t('auth.different') }}
    </button>
  </div>
  <form v-else @submit="onSubmit">
    <h1 :style="{ margin: '0 0 0.25rem', fontSize: '20px' }">{{ t('auth.signIn', { app: appName }) }}</h1>
    <p :style="{ margin: '0 0 var(--space-lg, 1.5rem)', color: 'var(--color-muted)', fontSize: '14px' }">
      {{ t('auth.subtitle') }}
    </p>
    <label :style="{ display: 'block', fontSize: '13px', color: 'var(--color-muted)' }">
      {{ t('auth.email') }}
      <input
        type="email"
        required
        v-model="email"
        placeholder="you@example.com"
        autocomplete="email"
        :style="field"
      />
    </label>
    <button type="submit" :disabled="state === 'sending'" :style="{ ...primaryBtn, opacity: state === 'sending' ? 0.7 : 1 }">
      {{ state === 'sending' ? t('auth.sending') : t('auth.send') }}
    </button>
    <p v-if="state === 'error'" :style="{ color: '#dc2626', fontSize: '13px', marginTop: 'var(--space-md, 1rem)' }">{{ t('auth.error') }}</p>
    <p :style="{ marginTop: 'var(--space-lg, 1.5rem)', color: 'var(--color-muted)', fontSize: '12px', lineHeight: 1.5 }">
      {{ t('auth.footer') }}
    </p>
  </form>
</template>

// packages/vike-react-auth/SignInForm.jsx
// <SignInForm> — posts an email to the vike-auth server tier's /auth/request
// endpoint and shows the "check your inbox" state. Styled with the theme's CSS
// variables (vike-themes) and localized via vike-react-i18n: every string is a
// t() lookup keyed under `auth.*`, and vike-react-auth ships the translations
// (see ./messages.js + +config.js), so the login UI follows the active locale.
import { useState } from 'react'
import { useTranslation } from 'vike-react-i18n'

const field = {
  width: '100%',
  boxSizing: 'border-box',
  padding: '0.6rem 0.7rem',
  marginTop: '0.35rem',
  borderRadius: 'var(--radius, 10px)',
  border: '1px solid var(--color-border)',
  background: 'var(--color-bg)',
  color: 'var(--color-text)',
  fontSize: 14,
}

const primaryBtn = {
  width: '100%',
  marginTop: 'var(--space-md, 1rem)',
  padding: '0.6rem 0.7rem',
  borderRadius: 'var(--radius, 10px)',
  border: '1px solid transparent',
  background: 'var(--color-primary)',
  color: 'var(--color-primary-text)',
  fontWeight: 600,
  fontSize: 14,
  cursor: 'pointer',
}

export function SignInForm({ action = '/auth/request', appName = 'Acme' }) {
  const { t } = useTranslation()
  const [email, setEmail] = useState('')
  const [state, setState] = useState('idle') // idle | sending | sent | error

  async function onSubmit(e) {
    e.preventDefault()
    setState('sending')
    try {
      const body = new FormData()
      body.set('email', email)
      const res = await fetch(action, { method: 'POST', body })
      setState(res.ok ? 'sent' : 'error')
    } catch {
      setState('error')
    }
  }

  if (state === 'sent') {
    return (
      <div>
        <h1 style={{ margin: '0 0 0.5rem', fontSize: 20 }}>{t('auth.inboxTitle')}</h1>
        <p style={{ color: 'var(--color-muted)', fontSize: 14, lineHeight: 1.6 }}>
          {t('auth.inboxBody', { email })} {t('auth.devNote')}
        </p>
        <button type="button" style={{ ...primaryBtn, background: 'transparent', color: 'var(--color-primary)', border: '1px solid var(--color-border)' }} onClick={() => setState('idle')}>
          {t('auth.different')}
        </button>
      </div>
    )
  }

  return (
    <form onSubmit={onSubmit}>
      <h1 style={{ margin: '0 0 0.25rem', fontSize: 20 }}>{t('auth.signIn', { app: appName })}</h1>
      <p style={{ margin: '0 0 var(--space-lg, 1.5rem)', color: 'var(--color-muted)', fontSize: 14 }}>
        {t('auth.subtitle')}
      </p>
      <label style={{ display: 'block', fontSize: 13, color: 'var(--color-muted)' }}>
        {t('auth.email')}
        <input
          type="email"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@example.com"
          autoComplete="email"
          style={field}
        />
      </label>
      <button type="submit" disabled={state === 'sending'} style={{ ...primaryBtn, opacity: state === 'sending' ? 0.7 : 1 }}>
        {state === 'sending' ? t('auth.sending') : t('auth.send')}
      </button>
      {state === 'error' && (
        <p style={{ color: '#dc2626', fontSize: 13, marginTop: 'var(--space-md, 1rem)' }}>{t('auth.error')}</p>
      )}
      <p style={{ marginTop: 'var(--space-lg, 1.5rem)', color: 'var(--color-muted)', fontSize: 12, lineHeight: 1.5 }}>
        {t('auth.footer')}
      </p>
    </form>
  )
}
