// packages/vike-notifications/vue/Bell.vue
<script setup>
// <NotificationsBell> — the Vue in-app feed control, the twin of
// vike-notifications/react/Bell. A bell with an unread badge that opens a feed list;
// "Mark all read" clears the badge. Thin wrapper over the framework-agnostic client
// helpers (vike-notifications/client); imports nothing server-side.
import { ref, onMounted, onUnmounted } from 'vue'
import { fetchFeed, markRead } from '../client.js'

const props = defineProps({
  label: { type: String, default: 'Notifications' },
  pollMs: { type: Number, default: 0 },
})

const items = ref([])
const unread = ref(0)
const open = ref(false)
const error = ref(null)
let timer = null

async function load() {
  try {
    const res = await fetchFeed({})
    items.value = res.items
    unread.value = res.unread
    error.value = null
  } catch (e) {
    error.value = e?.message || 'Failed to load'
  }
}

async function onMarkAll() {
  try {
    await markRead(null, {})
    await load()
  } catch (e) {
    error.value = e?.message || 'Failed to mark read'
  }
}

onMounted(() => {
  load()
  if (props.pollMs) timer = setInterval(load, props.pollMs)
})
onUnmounted(() => {
  if (timer) clearInterval(timer)
})
</script>

<template>
  <span :style="{ position: 'relative', display: 'inline-flex', alignItems: 'center' }">
    <button
      type="button"
      :aria-label="label"
      @click="open = !open"
      :style="{
        position: 'relative',
        padding: '0.35rem 0.6rem',
        borderRadius: 'var(--radius, 10px)',
        border: '1px solid var(--color-border)',
        background: 'var(--color-surface)',
        color: 'var(--color-text)',
        fontSize: '15px',
        cursor: 'pointer',
      }"
    >
      &#x1F514;
      <span
        v-if="unread > 0"
        :style="{
          position: 'absolute',
          top: '-6px',
          right: '-6px',
          minWidth: '16px',
          height: '16px',
          padding: '0 4px',
          borderRadius: '999px',
          background: '#dc2626',
          color: '#fff',
          fontSize: '10px',
          lineHeight: '16px',
          textAlign: 'center',
        }"
        >{{ unread > 99 ? '99+' : unread }}</span
      >
    </button>

    <div
      v-if="open"
      :style="{
        position: 'absolute',
        top: 'calc(100% + 8px)',
        right: 0,
        width: '320px',
        maxHeight: '380px',
        overflowY: 'auto',
        background: 'var(--color-surface)',
        border: '1px solid var(--color-border)',
        borderRadius: 'var(--radius, 10px)',
        boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
        zIndex: 50,
      }"
    >
      <div
        :style="{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '0.6rem 0.75rem',
          borderBottom: '1px solid var(--color-border)',
          fontSize: '13px',
          fontWeight: 600,
        }"
      >
        <span>{{ label }}</span>
        <button
          v-if="unread > 0"
          type="button"
          @click="onMarkAll"
          :style="{ border: 'none', background: 'none', color: 'var(--color-primary)', fontSize: '12px', cursor: 'pointer' }"
        >
          Mark all read
        </button>
      </div>

      <div v-if="error" :style="{ padding: '0.6rem 0.75rem', color: '#dc2626', fontSize: '12px' }">{{ error }}</div>

      <div v-if="items.length === 0" :style="{ padding: '1rem 0.75rem', color: 'var(--color-muted)', fontSize: '13px' }">
        Nothing yet
      </div>
      <div
        v-else
        v-for="n in items"
        :key="n.id"
        :style="{
          padding: '0.6rem 0.75rem',
          borderBottom: '1px solid var(--color-border)',
          background: n.read ? 'transparent' : 'var(--color-primary-soft, rgba(59,130,246,0.08))',
          fontSize: '13px',
        }"
      >
        <div :style="{ fontWeight: n.read ? 400 : 600 }">{{ n.data?.title ?? n.type }}</div>
        <div v-if="n.data?.body" :style="{ color: 'var(--color-muted)', marginTop: '2px' }">{{ n.data.body }}</div>
      </div>
    </div>
  </span>
</template>

// packages/vike-notifications/react/Bell.jsx
// <NotificationsBell> — the React in-app feed control. A bell with an unread badge that
// opens a feed list; clicking "Mark all read" clears the badge. Thin wrapper over the
// framework-agnostic client helpers (vike-notifications/client); imports nothing
// server-side, so it is safe in the client bundle.
import { useState, useEffect, useCallback } from 'react'
import { fetchFeed, markRead } from '../client.js'

export function NotificationsBell({ label = 'Notifications', pollMs = 0 }) {
  const [items, setItems] = useState([])
  const [unread, setUnread] = useState(0)
  const [open, setOpen] = useState(false)
  const [error, setError] = useState(null)

  const load = useCallback(async () => {
    try {
      const { items, unread } = await fetchFeed({})
      setItems(items)
      setUnread(unread)
      setError(null)
    } catch (e) {
      setError(e?.message || 'Failed to load')
    }
  }, [])

  useEffect(() => {
    load()
    if (!pollMs) return undefined
    const id = setInterval(load, pollMs)
    return () => clearInterval(id)
  }, [load, pollMs])

  async function onMarkAll() {
    try {
      await markRead(null, {})
      await load()
    } catch (e) {
      setError(e?.message || 'Failed to mark read')
    }
  }

  return (
    <span style={{ position: 'relative', display: 'inline-flex', alignItems: 'center' }}>
      <button
        type="button"
        aria-label={label}
        onClick={() => setOpen((o) => !o)}
        style={{
          position: 'relative',
          padding: '0.35rem 0.6rem',
          borderRadius: 'var(--radius, 10px)',
          border: '1px solid var(--color-border)',
          background: 'var(--color-surface)',
          color: 'var(--color-text)',
          fontSize: 15,
          cursor: 'pointer',
        }}
      >
        {'\u{1F514}'}
        {unread > 0 && (
          <span
            style={{
              position: 'absolute',
              top: -6,
              right: -6,
              minWidth: 16,
              height: 16,
              padding: '0 4px',
              borderRadius: 999,
              background: '#dc2626',
              color: '#fff',
              fontSize: 10,
              lineHeight: '16px',
              textAlign: 'center',
            }}
          >
            {unread > 99 ? '99+' : unread}
          </span>
        )}
      </button>

      {open && (
        <div
          style={{
            position: 'absolute',
            top: 'calc(100% + 8px)',
            right: 0,
            width: 320,
            maxHeight: 380,
            overflowY: 'auto',
            background: 'var(--color-surface)',
            border: '1px solid var(--color-border)',
            borderRadius: 'var(--radius, 10px)',
            boxShadow: '0 8px 24px rgba(0,0,0,0.12)',
            zIndex: 50,
          }}
        >
          <div
            style={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              padding: '0.6rem 0.75rem',
              borderBottom: '1px solid var(--color-border)',
              fontSize: 13,
              fontWeight: 600,
            }}
          >
            <span>{label}</span>
            {unread > 0 && (
              <button
                type="button"
                onClick={onMarkAll}
                style={{ border: 'none', background: 'none', color: 'var(--color-primary)', fontSize: 12, cursor: 'pointer' }}
              >
                Mark all read
              </button>
            )}
          </div>

          {error && <div style={{ padding: '0.6rem 0.75rem', color: '#dc2626', fontSize: 12 }}>{error}</div>}

          {items.length === 0 ? (
            <div style={{ padding: '1rem 0.75rem', color: 'var(--color-muted)', fontSize: 13 }}>Nothing yet</div>
          ) : (
            items.map((n) => (
              <div
                key={n.id}
                style={{
                  padding: '0.6rem 0.75rem',
                  borderBottom: '1px solid var(--color-border)',
                  background: n.read ? 'transparent' : 'var(--color-primary-soft, rgba(59,130,246,0.08))',
                  fontSize: 13,
                }}
              >
                <div style={{ fontWeight: n.read ? 400 : 600 }}>{n.data?.title ?? n.type}</div>
                {n.data?.body && <div style={{ color: 'var(--color-muted)', marginTop: 2 }}>{n.data.body}</div>}
              </div>
            ))
          )}
        </div>
      )}
    </span>
  )
}

export default NotificationsBell
